### ISSUE TITLE
redmine 1.3 support

### ISSUE THREAD

**Issue by lucasmcastro** [resilva/Redmine-Fields-permissions#3]
Any chance this works with redmine 1.3?

**Comment by resilva** [comment]
This issue is related to this one : https://github.com/resilva/Redmine-Fields-permissions/issues/2

This plugin probably won't works with 1.3 right now, when i've some time i'll work on this issue.

**Comment by lucasmcastro** [comment]
ok thanks

can i help you in solving this? I really never developed for redmine but i know rails and if you point directions i can work on it =)

**Comment by resilva** [comment]
To be honnest i cant give you some directions because i actually don't know how i'll upgrade, the only way i can see is the post of xeagle2 on the issue 2, so if you understand is post you can give a try :D i'll do my best to understand it and try to fix the issue when i have the time too :)

Thanks.
